# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            SLACKHA
tagline:          'Software Library for Accelerating Chemical Kinetics on Hybrid'
description:      ''
url:              http://slackha.github.io/
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:     Kyle Niemeyer
  url:      http://kyleniemeyer.com
  email:    kyle.niemeyer@gmail.com

github:
  repo: https://github.com/SLACKHA/slackha

kramdown:
   input: GFM
   hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate
