# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            SLACKHA
tagline:          'Software Library for Accelerating Chemical Kinetics on Hybrid'
description:      ''
url:              http://slackha.github.io/
baseurl:          /

author:
  name: 'Kyle Niemeyer'
  url: http://kyleniemeyer.com
  email: kyle.niemeyer@gmail.com


github:
  repo: https://github.com/SLACKHA/slackha

kramdown:
   input: GFM
   hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate
